language: python

python:
  - 3.7

services:
  - docker

install:
  - pip install coverage==4.5.4
  - pip install python-coveralls
  - docker run --name avalon-mongo -d mongo
  - . build_docker.sh

script:
  - . build_docker.sh
  - . test_docker.sh
  - . build_docs.sh

after_success:
  - coverage combine
  - coveralls

before_deploy:
  - sudo chmod -R 777 docs/build/
  - cd docs/build
  - touch .nojekyll
  - ls -l

deploy:
  provider: pages
  local-dir: docs/build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
