language: python

python:
  - 2.7

services:
  - docker

install:
  - docker run --name avalon-mongo -d mongo
  - docker build -t avalon/core -f Dockerfile-maya2016 .

script:
  - . test_docker.sh
  - . build_docs.sh

before_deploy:
  - sudo chmod -R 777 docs/build/
  - cd docs/build
  - touch .nojekyll
  - ls -l

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master